NETFN_NAMES = {
    0x00: "Chassis",
    0x02: "Bridge",
    0x04: "Sensor/Event",
    0x06: "App",
    0x08: "Firmware",
    0x0A: "Storage",
    0x0C: "Transport",
    0x2C: "Group Extension",
    0x2E: "OEM/Group",
}

# COMMANDS[netfn][cmd] = (name, brief_description)
COMMANDS = {
    0x00: {  # Chassis (IPMI 2.0 Table 22-1)
        0x00: ("Get Chassis Capabilities", "chassis 支援功能旗標"),
        0x01: ("Get Chassis Status", "power / fan / drive fault / restore policy"),
        0x02: ("Chassis Control", "power on/off/cycle/reset/soft-off/diagnostic interrupt"),
        0x03: ("Chassis Reset", ""),
        0x04: ("Chassis Identify", "chassis identify LED 控制"),
        0x05: ("Set Chassis Capabilities", ""),
        0x06: ("Set Power Restore Policy", ""),
        0x07: ("Get System Restart Cause", "上次重啟原因"),
        0x08: ("Set System Boot Options", "設定 BIOS boot flags"),
        0x09: ("Get System Boot Options", "讀取 boot flags"),
        0x0A: ("Set Front Panel Button Enables", ""),
        0x0B: ("Set Power Cycle Interval", ""),
        0x0F: ("Get POH Counter", "Power-on Hours"),
    },
    0x04: {  # Sensor/Event
        0x00: ("Set Event Receiver", ""),
        0x01: ("Get Event Receiver", ""),
        0x02: ("Platform Event", "傳入 Platform Event Message"),
        0x20: ("Get PEF Capabilities", ""),
        0x21: ("Arm PEF Postpone Timer", ""),
        0x22: ("Set PEF Configuration Parameters", ""),
        0x23: ("Get PEF Configuration Parameters", ""),
        0x24: ("Set Last Processed Event ID", ""),
        0x25: ("Get Last Processed Event ID", ""),
        0x26: ("Alert Immediate", ""),
        0x27: ("PET Acknowledge", ""),
        0x28: ("Set Sensor Hysteresis", ""),
        0x29: ("Get Sensor Hysteresis", ""),
        0x2A: ("Set Sensor Threshold", ""),
        0x2B: ("Get Sensor Threshold", ""),
        0x2C: ("Set Sensor Event Enable", ""),
        0x2D: ("Get Sensor Reading", "讀取單一 sensor 值 + status bytes"),
        0x2E: ("Re-arm Sensor Events", ""),
        0x2F: ("Get Sensor Type", "取得 sensor type code"),
        0x30: ("Set Sensor Reading and Event Status", ""),
    },
    0x06: {  # App
        0x01: ("Get Device ID", "BMC firmware version, IPMI version, device capabilities, Manufacturer/Product ID"),
        0x02: ("Cold Reset", "BMC cold reset（重新初始化）"),
        0x03: ("Warm Reset", "BMC warm reset（保留 session）"),
        0x04: ("Get Self Test Results", "BMC 自我測試：0x55=pass, 0x56=fail+reason"),
        0x05: ("Manufacturing Test On", ""),
        0x06: ("Set ACPI Power State", ""),
        0x07: ("Get ACPI Power State", ""),
        0x08: ("Get Device GUID", "128-bit GUID"),
        0x22: ("Reset Watchdog Timer", ""),
        0x24: ("Set Watchdog Timer", ""),
        0x25: ("Get Watchdog Timer", "watchdog 設定與狀態"),
        0x2E: ("Set BMC Global Enables", ""),
        0x2F: ("Get BMC Global Enables", ""),
        0x30: ("Clear Message Flags", ""),
        0x31: ("Get Message Flags", ""),
        0x37: ("Send Message", ""),
        0x38: ("Read Event Message Buffer", ""),
        0x3E: ("Get System GUID", "系統 GUID"),
        0x45: ("Set User Name", ""),
        0x46: ("Get User Name", ""),
        0x47: ("Set User Password", ""),
        0x48: ("Activate Payload", "RMCP+ payload 啟用（SOL 等）"),
        0x49: ("Deactivate Payload", ""),
        0x4A: ("Get Payload Activation Status", ""),
        0x4B: ("Get Payload Instance Info", ""),
        0x4C: ("Send Payload", ""),
        0x58: ("Get Channel Authentication Capabilities", ""),
        0x59: ("Get Session Challenge", "IPMI 1.5 session init"),
        0x5A: ("Activate Session", ""),
        0x5B: ("Set Session Privilege Level", ""),
        0x5C: ("Close Session", ""),
        0x5D: ("Get Session Info", ""),
        0x60: ("Set Channel Access", ""),
        0x61: ("Get Channel Access", "channel 的 auth / access mode"),
        0x62: ("Get Channel Info Command", "channel medium type / protocol"),
        0x63: ("Set User Access Command", ""),
        0x64: ("Get User Access Command", ""),
    },
    0x0A: {  # Storage
        0x10: ("Get FRU Inventory Area Info", "FRU 資料區大小與存取方式"),
        0x11: ("Read FRU Data", "讀取 FRU binary 資料"),
        0x12: ("Write FRU Data", "寫入 FRU 資料"),
        0x20: ("Get SDR Repository Info", "SDR 版本、record 數量、free space"),
        0x21: ("Get SDR Repository Allocation Info", ""),
        0x22: ("Reserve SDR Repository", "取得 reservation ID"),
        0x23: ("Get SDR", "讀取單筆 SDR record"),
        0x24: ("Add SDR", ""),
        0x25: ("Partial Add SDR", ""),
        0x26: ("Delete SDR", ""),
        0x27: ("Clear SDR Repository", ""),
        0x28: ("Get SDR Repository Time", ""),
        0x29: ("Set SDR Repository Time", ""),
        0x48: ("Get SEL Info", "SEL record 數、free space、時間戳"),
        0x49: ("Get SEL Allocation Info", ""),
        0x4A: ("Reserve SEL", ""),
        0x4B: ("Get SEL Entry", "讀取單筆 16-byte SEL record"),
        0x4C: ("Add SEL Entry", ""),
        0x4D: ("Partial Add SEL Entry", ""),
        0x4E: ("Delete SEL Entry", ""),
        0x4F: ("Clear SEL", "清除整個 SEL"),
        0x50: ("Get SEL Time", ""),
        0x51: ("Set SEL Time", ""),
    },
    0x0C: {  # Transport
        0x01: ("Set LAN Configuration Parameters", "IP / netmask / gateway / VLAN / RMCP port"),
        0x02: ("Get LAN Configuration Parameters", ""),
        0x03: ("Suspend BMC ARPs", ""),
        0x04: ("Get IP/UDP/RMCP Statistics", ""),
        0x10: ("Set Serial/Modem Configuration", ""),
        0x11: ("Get Serial/Modem Configuration", ""),
    },
}
